/**
 * Anchor program clients.
 * IDLs are generated by `anchor build` — stubs return null until built.
 */
import { Connection, PublicKey, SystemProgram, Transaction } from '@solana/web3.js'
import type { AnchorWallet } from '@solana/wallet-adapter-react'

export interface ScoreEntry {
  player: string
  score: number
  timestamp: number
}

export interface LeaderboardData {
  gameId: number
  entries: ScoreEntry[]
  totalSubmissions: number
}

/** Fetch leaderboard account data (mock until IDL is available) */
export async function fetchLeaderboard(
  _connection: Connection,
  leaderboardAddress: string,
): Promise<LeaderboardData | null> {
  // TODO: replace with Anchor program.account.leaderboard.fetch(leaderboardAddress)
  // after `anchor build` generates IDLs
  void leaderboardAddress
  return null
}

/** Commit score hash on-chain before reveal */
export async function commitScore(
  connection: Connection,
  wallet: AnchorWallet,
  gameId: bigint,
  commitmentHash: Uint8Array,
): Promise<string> {
  // TODO: replace with leaderboard program instruction after IDL generation
  void connection
  void wallet
  void gameId
  void commitmentHash
  throw new Error('Leaderboard program not deployed yet — run `anchor build` first')
}

/** Reveal score and insert into leaderboard */
export async function revealScore(
  connection: Connection,
  wallet: AnchorWallet,
  gameId: bigint,
  score: bigint,
  nonce: Uint8Array,
): Promise<string> {
  void connection
  void wallet
  void gameId
  void score
  void nonce
  throw new Error('Leaderboard program not deployed yet — run `anchor build` first')
}

/** Claim SPL token reward for score tier */
export async function claimReward(
  connection: Connection,
  wallet: AnchorWallet,
  gameId: bigint,
  score: bigint,
): Promise<string> {
  void connection
  void wallet
  void gameId
  void score
  throw new Error('RewardVault program not deployed yet — run `anchor build` first')
}

/** Send SOL tip to creator's tip jar */
export async function tipSol(
  connection: Connection,
  wallet: AnchorWallet,
  creatorAddress: string,
  lamports: number,
): Promise<string> {
  void creatorAddress
  // Simple transfer for now — replace with tip_jar instruction after IDL generation
  const tx = new Transaction().add(
    SystemProgram.transfer({
      fromPubkey: wallet.publicKey,
      toPubkey: new PublicKey(creatorAddress),
      lamports,
    }),
  )
  const { blockhash } = await connection.getLatestBlockhash()
  tx.recentBlockhash = blockhash
  tx.feePayer = wallet.publicKey
  const signed = await wallet.signTransaction(tx)
  return connection.sendRawTransaction(signed.serialize())
}

/** Register a new game on-chain */
export async function registerGame(
  _connection: Connection,
  _wallet: AnchorWallet,
  _params: {
    gameId: bigint
    name: string
    description: string
    slug: string
    thumbnailUri: string
    tipJar: PublicKey
    leaderboard: PublicKey
    rewardMint: PublicKey
  },
): Promise<string> {
  throw new Error('GameRegistry program not deployed yet — run `anchor build` first')
}
